import type { Task, User, Category, Aufgabe } from "./types";

interface UserWithTasks extends User {
  aufgabe?: Aufgabe[];
  tasks?: Task[];
}

const Users: UserWithTasks[] = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "leanne@example.com",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
      geo: { lat: "-37.3159", lng: "81.1496" },
    },
    phone: "1-770-736-8031",
    website: "leanne.org",
    company: {
      name: "Google",
      catchPhrase: "Multi-layered client-server neural-net",
      bs: "harness real-time e-markets",
    },
    description:
      "Innovatives Unternehmen im Bereich Technologie und Entwicklung.",
    imageURL: "/logos/google.jpeg",
    tasks: [],
    aufgabe: [],
    admin: true,
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
  {
    id: 52,
    name: "Ervin Howell",
    username: "Antonette",
    email: "ervin@example.com",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
      geo: { lat: "-43.9509", lng: "-34.4618" },
    },
    phone: "010-692-6593",
    website: "ervin.net",
    company: {
      name: "JPMorgan Chase",
      catchPhrase: "Proactive didactic contingency",
      bs: "synergize scalable supply-chains",
    },
    description: "Führender Anbieter von Finanzdienstleistungen.",
    imageURL: "/logos/jpmorgan.png",
    tasks: [],
    aufgabe: [],
    admin: true,
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "clementine@example.com",
    address: {
      street: "Douglas Extension",
      suite: "Suite 847",
      city: "McKenziehaven",
      zipcode: "59590-4157",
      geo: { lat: "-68.6102", lng: "-47.0653" },
    },
    phone: "1-463-123-4447",
    website: "clementine.info",
    company: {
      name: "Siemens",
      catchPhrase: "Face to face bifurcated interface",
      bs: "e-enable strategic applications",
    },
    description: "Spezialist für nachhaltige Energielösungen.",
    imageURL: "/logos/siemens.jpeg",
    tasks: [],
    aufgabe: [],
    admin: true,
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "patricia@example.com",
    address: {
      street: "Hoeger Mall",
      suite: "Apt. 692",
      city: "South Elvis",
      zipcode: "53919-4257",
      geo: { lat: "29.4572", lng: "-164.2990" },
    },
    phone: "493-170-9623",
    website: "patricia.biz",
    company: {
      name: "DHL",
      catchPhrase: "Multi-tiered zero tolerance productivity",
      bs: "transition cutting-edge web services",
    },
    description: "Globaler Dienstleister für Logistik und Transport.",
    imageURL: "/logos/dhl.png",
    tasks: [],
    aufgabe: [],
    admin: true,
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "chelsey@example.com",
    address: {
      street: "Skiles Walks",
      suite: "Suite 351",
      city: "Roscoeview",
      zipcode: "33263",
      geo: { lat: "-31.8129", lng: "62.5342" },
    },
    phone: "(254)954-1289",
    website: "chelsey.info",
    company: {
      name: "Procter & Gamble",
      catchPhrase: "User-centric fault-tolerant solution",
      bs: "revolutionize end-to-end systems",
    },
    description: "Hersteller von hochwertigen Konsumgütern.",
    imageURL: "/logos/procter.jpeg",
    tasks: [],
    aufgabe: [],
    admin: false,
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
  {
    id: 6,
    name: "Dennis Schulist",
    username: "Leopoldo",
    email: "dennis@example.com",
    address: {
      street: "Norberto Crossing",
      suite: "Apt. 950",
      city: "South Christy",
      zipcode: "23505-1337",
      geo: { lat: "-71.4197", lng: "71.7478" },
    },
    phone: "1-477-935-8478",
    website: "dennis.org",
    company: {
      name: "Cerner",
      catchPhrase: "Synchronised bottom-line interface",
      bs: "e-enable innovative applications",
    },
    description: "Innovativer Softwareanbieter im Gesundheitsbereich.",
    imageURL: "/logos/cerner.jpeg",
    tasks: [],
    aufgabe: [],
    admin: false,
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn",
    email: "kurtis@example.com",
    address: {
      street: "Rex Trail",
      suite: "Suite 280",
      city: "Howemouth",
      zipcode: "58804-1099",
      geo: { lat: "24.8918", lng: "21.8984" },
    },
    phone: "210.067.6132",
    website: "kurtis.io",
    company: {
      name: "Accenture",
      catchPhrase: "Implemented secondary concept",
      bs: "aggregate real-time technologies",
    },
    description: "Beratung und professionelle Dienstleistungen.",
    imageURL: "/logos/accentu.png",
    tasks: [],
    aufgabe: [],
    admin: false,
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime",
    email: "nicholas@example.com",
    address: {
      street: "Ellsworth Summit",
      suite: "Suite 729",
      city: "Aliyaview",
      zipcode: "45169",
      geo: { lat: "-14.3990", lng: "-120.7677" },
    },
    phone: "586.493.6943",
    website: "nicholas.biz",
    company: {
      name: "Intel",
      catchPhrase: "Centralized empowering task-force",
      bs: "target end-to-end models",
    },
    description: "Führender Chip-Hersteller weltweit.",
    imageURL: "/logos/intel.jpeg",
    tasks: [],
    admin: false,
    aufgabe: [],
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "glenna@example.com",
    address: {
      street: "Dayna Park",
      suite: "Suite 449",
      city: "Bartholomebury",
      zipcode: "76495-3109",
      geo: { lat: "24.6463", lng: "-168.8889" },
    },
    phone: "(775)976-6794",
    website: "glenna.org",
    company: {
      name: "Bayer",
      catchPhrase: "User-centric fault-tolerant solution",
      bs: "revolutionize end-to-end systems",
    },
    description: "Pharmaunternehmen mit globaler Reichweite.",
    imageURL: "/logos/bayern.png",
    tasks: [],
    aufgabe: [],
    admin: false,
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah",
    email: "clementina@example.com",
    address: {
      street: "Kattie Turnpike",
      suite: "Suite 198",
      city: "Lebsackbury",
      zipcode: "31428-2261",
      geo: { lat: "-38.2386", lng: "57.2232" },
    },
    phone: "024-648-3804",
    website: "clementina.biz",
    company: {
      name: "BMW",
      catchPhrase: "User-centric fault-tolerant solution",
      bs: "revolutionize end-to-end systems",
    },
    description: "Premium Autohersteller mit Fokus auf Innovation.",
    imageURL: "/logos/bwm.jpeg",
    tasks: [],
    aufgabe: [],
    admin: false,
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
  {
    id: 125,
    name: "Test Admin",
    username: "adminUser",
    email: "admin@example.com",
    address: {
      street: "Test Street",
      suite: "Suite 101",
      city: "Testville",
      zipcode: "12345-6789",
      geo: { lat: "40.7128", lng: "-74.0060" },
    },
    phone: "555-123-4567",
    website: "adminportal.test",
    company: {
      name: "TestCorp",
      catchPhrase: "Leading the future of testing",
      bs: "scalable test-driven development",
    },
    description:
      "Test user with full administrative privileges. Responsible for managing all test data and system configurations.",
    imageURL: "/logos/test.jpeg",
    tasks: [],
    aufgabe: [],
    admin: true,
    password:
      "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
  },
];

const Categories: Category[] = [
  {
    id: 31,
    name: "Marketing",
    subcategories: [
      { id: "seo", name: "SEO" },
      { id: "google_ads", name: "Google Ads" },
      { id: "social_media", name: "Social Media" },
    ],
  },
  {
    id: 2,
    name: "Vertrieb",
    subcategories: [
      { id: "cold_calls", name: "Cold Calls" },
      { id: "cold_mails", name: "Cold Mails" },
      { id: "lead_setting", name: "Leadqualifizierung / Setting" },
    ],
  },
  {
    id: 3,
    name: "Fulfillment",
    subcategories: [
      { id: "pf_design", name: "PF Design" },
      { id: "pdf_programmierung", name: "PDF Programmierung" },
      { id: "webformula", name: "Webformula" },
    ],
  },
];

export { Users, Categories };
